name: SDB

on:
    push:
        branches: [$default-branch]
    pull_request:
        branches: [$default-branch]

jobs:
    build:
        runs-on: ubuntu-20.04
        steps:
            - name: Install dependencies
              run: |
                  sudo apt --assume-yes update
                  sudo apt install ninja-build

            - name: Install Meson
              run: pip3 install -U meson

            - uses: actions/checkout@v2
            - name: Running mmap build
              run: |
                  meson build
                  ninja -C build

            - name: Running non-mmap build
              env:
                  CFLAGS: -DUSE_MMAN=-0
                  VERBOSE: 1
              run: |
                  rm -rf build
                  meson build
                  ninja -C build
